# Generated by Django 5.1.2 on 2024-11-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medico', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.CharField(max_length=100)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos', to='server.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_novo', models.BooleanField(default=True)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('ocupacao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('duracao', models.DurationField()),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('incidente', models.BooleanField(default=False)),
                ('satisfacao', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('enviado', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('summary', models.TextField(blank=True, null=True)),
                ('satisfaction_score', models.FloatField(null=True)),
                ('quality_index', models.FloatField(null=True)),
                ('key_topics', models.JSONField(default=list)),
                ('marketing_opportunities', models.JSONField(default=list)),
                ('ai_processed', models.BooleanField(default=False)),
                ('transcription_file', models.FileField(blank=True, null=True, upload_to='transcriptions/%Y/%m/%d/')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summaries/%Y/%m/%d/')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.paciente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.servico')),
            ],
        ),
    ]
