# Generated by Django 5.1.2 on 2024-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_add_pipedrive_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='pipedrive_api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
