# Generated by Django 5.1.2 on 2024-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='trusted_devices',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='two_factor_secret',
        ),
        migrations.AddField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='Nome não Definido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medico',
            name='pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
