# Generated by Django 5.1.2 on 2024-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_fix_servico'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servico',
            table='server_servico',
        ),
    ]
