# Generated by Django 5.1.2 on 2024-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_clinica_pipedrive_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ai_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='key_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='consulta',
            name='marketing_opportunities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='consulta',
            name='quality_index',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='satisfaction_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summaries/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='transcription_file',
            field=models.FileField(blank=True, null=True, upload_to='transcriptions/%Y/%m/%d/'),
        ),
    ]
