# Generated by Django 5.1.2 on 2024-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_consulta_ai_processed_consulta_key_topics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_dashboard_geral', 'Can view dashboard geral'), ('view_dashboard_clinica', 'Can view dashboard clínica'), ('gravar_consulta', 'Can gravar consulta')]},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='server_usuario',
        ),
    ]
