# Generated by Django 5.1.2 on 2024-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_duracao_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
