# Generated by Django 5.1.2 on 2024-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_clinicregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinica',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='pipedrive_api_token',
        ),
        migrations.AddField(
            model_name='clinica',
            name='address',
            field=models.CharField(default='Endereço não especificado', max_length=255),
        ),
        migrations.AddField(
            model_name='clinica',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='endereco',
            field=models.CharField(default='Endereço não especificado', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='password',
            field=models.CharField(default='dwahdwakjhAKJHDKJAWH2#34218$%', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='phone',
            field=models.CharField(default='+55 11 99999-9999', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinica',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Exemplo', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
