# Generated by Django 5.1.2 on 2024-11-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_fix_servico'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicoservico',
            table='server_medicoservico',
        ),
    ]
