# Generated by Django 5.1.2 on 2024-11-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_fix_medicoservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='servicos',
            field=models.ManyToManyField(related_name='medicos', through='server.MedicoServico', to='server.servico'),
        ),
    ]
