# Generated by Django 5.1.2 on 2024-11-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_medico_servicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='aspectos_emocionais',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='expectativas_paciente',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='experiencias_anteriores',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='interesse_tratamentos',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='motivacoes',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='preocupacoes_saude',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='problemas_relatados',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='procedimentos_desejados',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='produtos_interesse',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
