# Generated by Django 5.1.2 on 2024-11-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_consulta_aspectos_emocionais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_cadastro',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ultima_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
